### ISSUE TITLE
Memory leak with model loading

### ISSUE THREAD

**Issue by BanditSan** [THUDM/ImageReward#11]
I noticed that [image_reward.py](https://github.com/THUDM/ImageReward/blob/main/demo/sdwebui/image_reward.py) loads model durring `sdwebui` start-up. Thats is waste of memory when script is not beeing used. Model should only be loaded when script is activated durring Generation not on sdwebui start-up.

Also if you use `Reload UI` in settings it is loads model again without unloading data from previous start.
After 5 UI reloads no free vram left:
![image](https://user-images.githubusercontent.com/6743235/236533355-6ec8323e-d627-4709-b4ee-2923d9cb74e9.png)

By using `Settings > Actions > Unload SD checkpoint to free VRAM` only last loaded model is unloaded. Older loads sits in vram like garbage data.

**Comment by tongyx361** [comment]
Thank you for raising the issue!
To address the issue you raised, we have updated the ImageReward Scorer in SD Web UI with the following features:
- ImageReward model will not be loaded until **first script run**.
- **Reload UI** does not reload the model nor unload it, but reuses the currently loaded model (if it exists).
- A **"Unload Model "** button is provided to manually unload the currently loaded model.

These updates will be available soon. Stay tuned!

Also, it's worth mentioning that `Settings > Actions > Unload SD checkpoint to free VRAM` is supposed to unload the currently loaded Stable Diffusion model, not any ImageReward model.
But the issue you raised is really important. Thanks again for raising the issue and helping us make this work better!

**Comment by BanditSan** [comment]
@tongyx361 Latest script update fails to load.
```python
Error loading script: image_reward.py
Traceback (most recent call last):
  File "/srv/sd-webui/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/srv/sd-webui/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/srv/sd-webui/stable-diffusion-webui/scripts/image_reward.py", line 14
    >>>>>>> 45d635454c2dbc31fa1e75a4ccb8dd1031183974
             ^
SyntaxError: invalid decimal literal
```

With my very basic python knowledge cannot tell is this a normal line of code or just code patch went wrong?
```>>>>>>> 45d635454c2dbc31fa1e75a4ccb8dd1031183974```

This looks more like code merging did some kinda oops and executed incorrect

**Comment by tongyx361** [comment]
> @tongyx361 Latest script update fails to load.
> 
> ```python
> Error loading script: image_reward.py
> Traceback (most recent call last):
>   File "/srv/sd-webui/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
>     script_module = script_loading.load_module(scriptfile.path)
>   File "/srv/sd-webui/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 879, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 1017, in get_code
>   File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/srv/sd-webui/stable-diffusion-webui/scripts/image_reward.py", line 14
>     >>>>>>> 45d635454c2dbc31fa1e75a4ccb8dd1031183974
>              ^
> SyntaxError: invalid decimal literal
> ```
> 
> With my very basic python knowledge cannot tell is this a normal line of code or just code patch went wrong? `>>>>>>> 45d635454c2dbc31fa1e75a4ccb8dd1031183974`
> 
> This looks more like code merging did some kinda oops and executed incorrect

Sorry for my foolish mistake of forgetting resolving the conflicts between new and old code.
This problem will be solved soon in the newest PR.
