### ISSUE TITLE
Could you comment on what the "researcher" in Table 1 refers to?

### ISSUE THREAD

**Issue by sunwei925** [THUDM/ImageReward#12]
Hi,

Thanks for the excellent job! After reading the paper, I am not sure what the "researcher" in Table 1 refers to. Is that the label annotated by professional subjects? 

Best!

**Comment by xujz18** [comment]
The "researcher" denotes authors who design the annotation and inspectors who double-check each annotation.

**Comment by sunwei925** [comment]
Got it! Thanks very much!
