### ISSUE TITLE
BLIP Tokenizer `max_length`

### ISSUE THREAD

**Issue by guyjacob** [THUDM/ImageReward#17]
Many thanks for sharing the code.

I was wondering why you're calling the tokenizer with `max_length=35`? Is there anything preventing me from relaxing this limit?
(Also noticed that for `CLIPScore` you don't impose the same limitation)

**Comment by xujz18** [comment]
Calling the tokenizer with max_length=35 is just to keep the same as settings of BLIP at https://github.com/salesforce/BLIP/blob/main/eval_retrieval_video.py#LL49C59-L49C59, it's worth trying relaxing the limit.

**Comment by guyjacob** [comment]
Understood. Thanks for the pointer.
