### ISSUE TITLE
关于score结果的疑问

### ISSUE THREAD

**Issue by mzp1121** [THUDM/ImageReward#22]
请问最终得分有什么具体的参考意义吗？还是说只是用来排序的？

**Comment by mzp1121** [comment]
那是否存在一个阈值？高于这个阈值，认为图像生成是ok的，低于这个阈值，生成是不好的

**Comment by xujz18** [comment]
这个阈值根据使用者的实际需求和所用数据集，可以人为设定，例如你可以根据分数筛选top5%、top10%、top50%，等等。
(Here is the English version of the answer) This threshold can be set artificially depending on the actual needs of the user and the data set used, e.g. you can filter top5%, top10%, top50%, etc. based on the score.
