### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by zcdliuwei** [THUDM/ImageReward#28]
Due to network issues, I was unable to download the model in the code, so I place the ImageReward.pt and med_config.json file locally and execute:
Model=RM. load (name="/home/lw/ImageRward/ckpt/ImageRward. pt", med_config="/home/lw/ImageRward/ckpt/med_config. json")

Then I received the following error message:
OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

May I ask how to solve this problem？

**Comment by zcdliuwei** [comment]
I solved it

**Comment by 37s** [comment]
> I solved it

How did you solve it?

**Comment by wenyi-zhh** [comment]
> I solved it

how can you solve it?
