### ISSUE TITLE
I can't understand the meaning of the code, especially why the red variable is set like this?

### ISSUE THREAD

**Issue by xyxxmb** [THUDM/ImageReward#32]
In code: ImageReward/ReFL.py lines 730~737

![image](https://github.com/THUDM/ImageReward/assets/23254965/8dc8d207-70a0-496a-983c-712b56a00ac5)

**Comment by xujz18** [comment]
![图片1](https://github.com/THUDM/ImageReward/assets/52482160/a03ba671-6d51-42cf-ac71-144c49f4f1ef)

**Comment by xyxxmb** [comment]
> ![图片1](https:user-images.githubusercontent.com/52482160/252148591-a03ba671-6d51-42cf-ac71-144c49f4f1ef.png)

According to the Algorithm 1 in this paper, I think the code should be:
`                    
latent_model_input = latents
latent_model_input = self.noise_scheduler.scale_model_input(latent_model_input, timesteps[mid_timestep])  
noise_pred = self.unet(
      latent_model_input,
      timesteps[mid_timestep],
      encoder_hidden_states=encoder_hidden_states,
).sample
pred_original_sample = self.noise_scheduler.step(noise_pred, timesteps[mid_timestep], latents).pred_original_sample.to(self.weight_dtype) 
`

What do you think?

**Comment by xyxxmb** [comment]
> ![图片1](https:user-images.githubusercontent.com/52482160/252148591-a03ba671-6d51-42cf-ac71-144c49f4f1ef.png)

According to the Algorithm 1 in this paper, I think the code should be:

latent_model_input = latents 
latent_model_input = self.noise_scheduler.scale_model_input(latent_model_input, timesteps[mid_timestep])   
noise_pred = self.unet( 
    latent_model_input, 
    timesteps[mid_timestep], 
    encoder_hidden_states=encoder_hidden_states, 
).sample 
pred_original_sample = self.noise_scheduler.step(noise_pred, timesteps[mid_timestep], latents).pred_original_sample.to(self.weight_dtype) 

What do you think?

**Comment by xujz18** [comment]
They are equal, `t` is equal to `mid_timestep` at line 737.

**Comment by xyxxmb** [comment]
> 

I think t = mid_timestep-1, and the param of unet is timesteps[mid_timestep] instead of mid_timestep

**Comment by xyxxmb** [comment]
> They are equal, `t` is equal to `mid_timestep` at line 737.

I think t = timesteps[mid_timestep-1], and the param of unet is timesteps[mid_timestep] instead of mid_timestep

**Comment by xujz18** [comment]
Yes you are right! There are some typo as you pointed out. Thanks a lot!
