### ISSUE TITLE
how is the score related with alignment?

### ISSUE THREAD

**Issue by Yuheng-Li** [THUDM/ImageReward#39]
From the paper, this metric seems a general purpose score measuring human preference. If I am only interested in image text alignment, it this metric suitable?

**Comment by xujz18** [comment]
DPOK: Reinforcement Learning for Fine-tuning Text-to-Image Diffusion Models (https://arxiv.org/pdf/2305.16381.pdf), this paper has explored it. In Appendix C (Investigation on ImageReward), the result is as follows.

**Comment by Yuheng-Li** [comment]
thanks
