### ISSUE TITLE
How to re-implement the result by using CLIP-score as the reward model?

### ISSUE THREAD

**Issue by Wallace-222** [THUDM/ImageReward#42]
Hello authors,
Thanks a lot for your wonderful work.
I want to know how to change the code and re-run it by using the CLIP-score as the reward model to have the baseline result?

**Comment by xujz18** [comment]
Please refer to [test.py](https://github.com/THUDM/ImageReward/blob/main/test.py), you can set `--model_type` as `CLIP`.
