### ISSUE TITLE
Auto1111 Script not showing up in scripts

### ISSUE THREAD

**Issue by harspeck** [THUDM/ImageReward#46]
Getting this upon loading auto1111:

{"payload":{"allShortcutsEnabled":true,"fileTree":{"sdwebui":{"items":[{"name":"image_reward.py","path":"sdwebui/image_reward.py","contentType":"file"}],"totalCount":1},"":{"items":[{"name":"ImageReward","path":"ImageReward","contentType":"directory"},{"name":"assets","path":"assets","contentType":"directory"},{"name":"benchmark","path":"benchmark","contentType":"directory"},{"name":"data","path":"data","contentType":"directory"},{"name":"figures","path":"figures","contentType":"directory"},{"name":"scripts","path":"scripts","contentType":"directory"},{"name":"sdwebui","path":"sdwebui","contentType":"directory"},{"name":"train","path":"train","contentType":"directory"},{"name":".gitignore","path":".gitignore","contentType":"file"},{"name":"LICENSE","path":"LICENSE","contentType":"file"},{"name":"README.md","path":"README.md","contentType":"file"},{"name":"example.py","path":"example.py","contentType":"file"},{"name":"refl.py","path":"refl.py","contentType":"file"},{"name":"requirements.txt","path":"requirements.txt","contentType":"file"},{"name":"requirements_refl.txt","path":"requirements_refl.txt","contentType":"file"},{"name":"setup.py","path":"setup.py","contentType":"file"},{"name":"test-benchmark.py","path":"test-benchmark.py","contentType":"file"},{"name":"test.py","path":"test.py","contentType":"file"}],"totalCount":18}},"fileTreeProcessingTime":4.689069,"foldersToFetch":[],"reducedMotionEnabled":"system","repo":{"id":622147274,"defaultBranch":"main","name":"ImageReward","ownerLogin":"THUDM","currentUserCanPush":false,"isFork":false,"isEmpty":false,"createdAt":"2023-04-01T04:04:17.000-05:00","ownerAvatar":"https://avatars.githubusercontent.com/u/48590610?v=4","public":true,"private":false,"isOrgOwned":true},"refInfo":{"name":"main","listCacheKey":"v0:1681308785.0","canEdit":true,"refType":"branch","currentOid":"a4a2336f4109509ad2cc9e8af4274f41a130004d"},"path":"sdwebui/image_reward.py","currentUser":{"id":27867421,"login":"harspeck","userEmail":"has245@cornell.edu"},"blob":{"rawLines":["import os","import subprocess","import sys","from pathlib import Path","","import gradio as gr","import modules.images as images","import modules.scripts as scripts","import torch","from huggingface_hub.constants import HUGGINGFACE_HUB_CACHE","from modules import sd_samplers, shared","from modules.processing import (","    Processed,","    StableDiffusionProcessing,","    create_infotext,","    process_images,",")","from modules.shared import cmd_opts, opts, state","","try:","    import ImageReward as reward","except ModuleNotFoundError as error:","    print('\"image-reward\" package has not been properly installed. Installing...')","    if subprocess.check_call([\"pip\", \"install\", \"image-reward\"]) == 0:","        print(f'\"image-reward\" package is successfully installed!')","        import ImageReward as reward","    else:","        print('\"image-reward\" package installation failed!')","        print(","            \"Please open an issue with full error message at https://github.com/THUDM/ImageReward/issues\"","        )","","","def unload_image_reward_model():","    del shared.image_reward_model","","","class Script(scripts.Script):","    def title(self):","        return \"ImageReward - generate human preference scores\"","","    def show(self, is_txt2img):","        return True","","    def ui(self, is_txt2img):","        with gr.Blocks():","            with gr.Row():","                gr.Markdown(","                    value=\"**Tip**: It will take a little time to **load** the ImageReward model before **the first generation**.\"","                )","            with gr.Row():","                with gr.Column():","                    filter_out_low_scores = gr.Checkbox(","                        value=False, label=\"Filter out images with low scores\"","                    )","                with gr.Column():","                    lower_score_limit = gr.Textbox(value=0, label=\"Lower score limit\")","            with gr.Row():","                gr.Markdown(","                    value=\"ImageReward model takes about **1,600 MB** of memory.\"","                )","            with gr.Row():","                unload_button = gr.Button(value=\"Unload Model From Memory\")","                unload_button.click(unload_image_reward_model)","        return [filter_out_low_scores, lower_score_limit]","","    def run(self, p, filter_out_low_scores, lower_score_limit):","        try:","            shared.image_reward_model  # if loaded, do nothing","        except AttributeError:","            # load the model","            if sys.platform == \"win32\":","                download_root = HUGGINGFACE_HUB_CACHE","            else:","                download_root = None","            print(f\"Loading ImageReward model from {download_root}...\")","            shared.image_reward_model = reward.load(","                \"ImageReward-v1.0\", download_root=download_root","            )  # using shared to make the model object global among modules","","        # preprocess parameters","        if lower_score_limit != \"\":","            lower_score_limit = float(lower_score_limit)","","        # generate images","        proc = process_images(p)","","        # score","        gens = proc.images","        with torch.no_grad():","            for img in gens:","                score = shared.image_reward_model.score(p.prompt, img)","                img.info[\"score\"] = score","                if img.info.get(\"parameters\") is None:","                    img.info[\"parameters\"] = f\"ImageReward Score: {score:.4f}\"","                else:","                    img.info[\"parameters\"] += f\"\\n ImageReward Score: {score:.4f}\"","","        # filter out images with scores lower than the lower limit","        if filter_out_low_scores:","            imgs = list(filter(lambda x: x.info[\"score\"] > lower_score_limit, gens))","        else:","            imgs = gens","","        # append score to info","        infotexts = [img.info[\"parameters\"] for img in imgs]","","        # sort to score","        img_info_list = list(zip(imgs, infotexts))","        img_info_list.sort(key=lambda x: x[0].info[\"score\"], reverse=True)","        imgs, infotexts = list(zip(*img_info_list))","","        # return Processed object","        return Processed(","            p=p,","            images_list=imgs,","            info=proc.info,","            seed=proc.seed,","            infotexts=infotexts,","            index_of_first_image=proc.index_of_first_image,","        )"],"stylingDirectives":[[{"start":0,"end":6,"cssClass":"pl-k"},{"start":7,"end":9,"cssClass":"pl-s1"}],[{"start":0,"end":6,"cssClass":"pl-k"},{"start":7,"end":17,"cssClass":"pl-s1"}],[{"start":0,"end":6,"cssClass":"pl-k"},{"start":7,"end":10,"cssClass":"pl-s1"}],[{"start":0,"end":4,"cssClass":"pl-k"},{"start":5,"end":12,"cssClass":"pl-s1"},{"start":13,"end":19,"cssClass":"pl-k"},{"start":20,"end":24,"cssClass":"pl-v"}],[],[{"start":0,"end":6,"cssClass":"pl-k"},{"start":7,"end":13,"cssClass":"pl-s1"},{"start":14,"end":16,"cssClass":"pl-k"},{"start":17,"end":19,"cssClass":"pl-s1"}],[{"start":0,"end":6,"cssClass":"pl-k"},{"start":7,"end":14,"cssClass":"pl-s1"},{"start":15,"end":21,"cssClass":"pl-s1"},{"start":22,"end":24,"cssClass":"pl-k"},{"start":25,"end":31,"cssClass":"pl-s1"}],[{"start":0,"end":6,"cssClass":"pl-k"},{"start":7,"end":14,"cssClass":"pl-s1"},{"start":15,"end":22,"cssClass":"pl-s1"},{"start":23,"end":25,"cssClass":"pl-k"},{"start":26,"end":33,"cssClass":"pl-s1"}],[{"start":0,"end":6,"cssClass":"pl-k"},{"start":7,"end":12,"cssClass":"pl-s1"}],[{"start":0,"end":4,"cssClass":"pl-k"},{"start":5,"end":20,"cssClass":"pl-s1"},{"start":21,"end":30,"cssClass":"pl-s1"},{"start":31,"end":37,"cssClass":"pl-k"},{"start":38,"end":59,"cssClass":"pl-v"}],[{"start":0,"end":4,"cssClass":"pl-k"},{"start":5,"end":12,"cssClass":"pl-s1"},{"start":13,"end":19,"cssClass":"pl-k"},{"start":20,"end":31,"cssClass":"pl-s1"},{"start":33,"end":39,"cssClass":"pl-s1"}],[{"start":0,"end":4,"cssClass":"pl-k"},{"start":5,"end":12,"cssClass":"pl-s1"},{"start":13,"end":23,"cssClass":"pl-s1"},{"start":24,"end":30,"cssClass":"pl-k"}],[{"start":4,"end":13,"cssClass":"pl-v"}],[{"start":4,"end":29,"cssClass":"pl-v"}],[{"start":4,"end":19,"cssClass":"pl-s1"}],[{"start":4,"end":18,"cssClass":"pl-s1"}],[],[{"start":0,"end":4,"cssClass":"pl-k"},{"start":5,"end":12,"cssClass":"pl-s1"},{"start":13,"end":19,"cssClass":"pl-s1"},{"start":20,"end":26,"cssClass":"pl-k"},{"start":27,"end":35,"cssClass":"pl-s1"},{"start":37,"end":41,"cssClass":"pl-s1"},{"start":43,"end":48,"cssClass":"pl-s1"}],[],[{"start":0,"end":3,"cssClass":"pl-k"}],[{"start":4,"end":10,"cssClass":"pl-k"},{"start":11,"end":22,"cssClass":"pl-v"},{"start":23,"end":25,"cssClass":"pl-k"},{"start":26,"end":32,"cssClass":"pl-s1"}],[{"start":0,"end":6,"cssClass":"pl-k"},{"start":7,"end":26,"cssClass":"pl-v"},{"start":27,"end":29,"cssClass":"pl-k"},{"start":30,"end":35,"cssClass":"pl-s1"}],[{"start":4,"end":9,"cssClass":"pl-en"},{"start":10,"end":81,"cssClass":"pl-s"}],[{"start":4,"end":6,"cssClass":"pl-k"},{"start":7,"end":17,"cssClass":"pl-s1"},{"start":18,"end":28,"cssClass":"pl-en"},{"start":30,"end":35,"cssClass":"pl-s"},{"start":37,"end":46,"cssClass":"pl-s"},{"start":48,"end":62,"cssClass":"pl-s"},{"start":65,"end":67,"cssClass":"pl-c1"},{"start":68,"end":69,"cssClass":"pl-c1"}],[{"start":8,"end":13,"cssClass":"pl-en"},{"start":14,"end":66,"cssClass":"pl-s"}],[{"start":8,"end":14,"cssClass":"pl-k"},{"start":15,"end":26,"cssClass":"pl-v"},{"start":27,"end":29,"cssClass":"pl-k"},{"start":30,"end":36,"cssClass":"pl-s1"}],[{"start":4,"end":8,"cssClass":"pl-k"}],[{"start":8,"end":13,"cssClass":"pl-en"},{"start":14,"end":59,"cssClass":"pl-s"}],[{"start":8,"end":13,"cssClass":"pl-en"}],[{"start":12,"end":105,"cssClass":"pl-s"}],[],[],[],[{"start":0,"end":3,"cssClass":"pl-k"},{"start":4,"end":29,"cssClass":"pl-en"}],[{"start":4,"end":7,"cssClass":"pl-k"},{"start":8,"end":14,"cssClass":"pl-s1"},{"start":15,"end":33,"cssClass":"pl-s1"}],[],[],[{"start":0,"end":5,"cssClass":"pl-k"},{"start":6,"end":12,"cssClass":"pl-v"},{"start":13,"end":20,"cssClass":"pl-s1"},{"start":21,"end":27,"cssClass":"pl-v"}],[{"start":4,"end":7,"cssClass":"pl-k"},{"start":8,"end":13,"cssClass":"pl-en"},{"start":14,"end":18,"cssClass":"pl-s1"}],[{"start":8,"end":14,"cssClass":"pl-k"},{"start":15,"end":63,"cssClass":"pl-s"}],[],[{"start":4,"end":7,"cssClass":"pl-k"},{"start":8,"end":12,"cssClass":"pl-en"},{"start":13,"end":17,"cssClass":"pl-s1"},{"start":19,"end":29,"cssClass":"pl-s1"}],[{"start":8,"end":14,"cssClass":"pl-k"},{"start":15,"end":19,"cssClass":"pl-c1"}],[],[{"start":4,"end":7,"cssClass":"pl-k"},{"start":8,"end":10,"cssClass":"pl-en"},{"start":11,"end":15,"cssClass":"pl-s1"},{"start":17,"end":27,"cssClass":"pl-s1"}],[{"start":8,"end":12,"cssClass":"pl-k"},{"start":13,"end":15,"cssClass":"pl-s1"},{"start":16,"end":22,"cssClass":"pl-v"}],[{"start":12,"end":16,"cssClass":"pl-k"},{"start":17,"end":19,"cssClass":"pl-s1"},{"start":20,"end":23,"cssClass":"pl-v"}],[{"start":16,"end":18,"cssClass":"pl-s1"},{"start":19,"end":27,"cssClass":"pl-v"}],[{"start":20,"end":25,"cssClass":"pl-s1"},{"start":25,"end":26,"cssClass":"pl-c1"},{"start":26,"end":130,"cssClass":"pl-s"}],[],[{"start":12,"end":16,"cssClass":"pl-k"},{"start":17,"end":19,"cssClass":"pl-s1"},{"start":20,"end":23,"cssClass":"pl-v"}],[{"start":16,"end":20,"cssClass":"pl-k"},{"start":21,"end":23,"cssClass":"pl-s1"},{"start":24,"end":30,"cssClass":"pl-v"}],[{"start":20,"end":41,"cssClass":"pl-s1"},{"start":42,"end":43,"cssClass":"pl-c1"},{"start":44,"end":46,"cssClass":"pl-s1"},{"start":47,"end":55,"cssClass":"pl-v"}],[{"start":24,"end":29,"cssClass":"pl-s1"},{"start":29,"end":30,"cssClass":"pl-c1"},{"start":30,"end":35,"cssClass":"pl-c1"},{"start":37,"end":42,"cssClass":"pl-s1"},{"start":42,"end":43,"cssClass":"pl-c1"},{"start":43,"end":78,"cssClass":"pl-s"}],[],[{"start":16,"end":20,"cssClass":"pl-k"},{"start":21,"end":23,"cssClass":"pl-s1"},{"start":24,"end":30,"cssClass":"pl-v"}],[{"start":20,"end":37,"cssClass":"pl-s1"},{"start":38,"end":39,"cssClass":"pl-c1"},{"start":40,"end":42,"cssClass":"pl-s1"},{"start":43,"end":50,"cssClass":"pl-v"},{"start":51,"end":56,"cssClass":"pl-s1"},{"start":56,"end":57,"cssClass":"pl-c1"},{"start":57,"end":58,"cssClass":"pl-c1"},{"start":60,"end":65,"cssClass":"pl-s1"},{"start":65,"end":66,"cssClass":"pl-c1"},{"start":66,"end":85,"cssClass":"pl-s"}],[{"start":12,"end":16,"cssClass":"pl-k"},{"start":17,"end":19,"cssClass":"pl-s1"},{"start":20,"end":23,"cssClass":"pl-v"}],[{"start":16,"end":18,"cssClass":"pl-s1"},{"start":19,"end":27,"cssClass":"pl-v"}],[{"start":20,"end":25,"cssClass":"pl-s1"},{"start":25,"end":26,"cssClass":"pl-c1"},{"start":26,"end":81,"cssClass":"pl-s"}],[],[{"start":12,"end":16,"cssClass":"pl-k"},{"start":17,"end":19,"cssClass":"pl-s1"},{"start":20,"end":23,"cssClass":"pl-v"}],[{"start":16,"end":29,"cssClass":"pl-s1"},{"start":30,"end":31,"cssClass":"pl-c1"},{"start":32,"end":34,"cssClass":"pl-s1"},{"start":35,"end":41,"cssClass":"pl-v"},{"start":42,"end":47,"cssClass":"pl-s1"},{"start":47,"end":48,"cssClass":"pl-c1"},{"start":48,"end":74,"cssClass":"pl-s"}],[{"start":16,"end":29,"cssClass":"pl-s1"},{"start":30,"end":35,"cssClass":"pl-en"},{"start":36,"end":61,"cssClass":"pl-s1"}],[{"start":8,"end":14,"cssClass":"pl-k"},{"start":16,"end":37,"cssClass":"pl-s1"},{"start":39,"end":56,"cssClass":"pl-s1"}],[],[{"start":4,"end":7,"cssClass":"pl-k"},{"start":8,"end":11,"cssClass":"pl-en"},{"start":12,"end":16,"cssClass":"pl-s1"},{"start":18,"end":19,"cssClass":"pl-s1"},{"start":21,"end":42,"cssClass":"pl-s1"},{"start":44,"end":61,"cssClass":"pl-s1"}],[{"start":8,"end":11,"cssClass":"pl-k"}],[{"start":12,"end":18,"cssClass":"pl-s1"},{"start":19,"end":37,"cssClass":"pl-s1"},{"start":39,"end":62,"cssClass":"pl-c"}],[{"start":8,"end":14,"cssClass":"pl-k"},{"start":15,"end":29,"cssClass":"pl-v"}],[{"start":12,"end":28,"cssClass":"pl-c"}],[{"start":12,"end":14,"cssClass":"pl-k"},{"start":15,"end":18,"cssClass":"pl-s1"},{"start":19,"end":27,"cssClass":"pl-s1"},{"start":28,"end":30,"cssClass":"pl-c1"},{"start":31,"end":38,"cssClass":"pl-s"}],[{"start":16,"end":29,"cssClass":"pl-s1"},{"start":30,"end":31,"cssClass":"pl-c1"},{"start":32,"end":53,"cssClass":"pl-v"}],[{"start":12,"end":16,"cssClass":"pl-k"}],[{"start":16,"end":29,"cssClass":"pl-s1"},{"start":30,"end":31,"cssClass":"pl-c1"},{"start":32,"end":36,"cssClass":"pl-c1"}],[{"start":12,"end":17,"cssClass":"pl-en"},{"start":18,"end":70,"cssClass":"pl-s"},{"start":51,"end":66,"cssClass":"pl-s1"},{"start":51,"end":52,"cssClass":"pl-kos"},{"start":52,"end":65,"cssClass":"pl-s1"},{"start":65,"end":66,"cssClass":"pl-kos"}],[{"start":12,"end":18,"cssClass":"pl-s1"},{"start":19,"end":37,"cssClass":"pl-s1"},{"start":38,"end":39,"cssClass":"pl-c1"},{"start":40,"end":46,"cssClass":"pl-s1"},{"start":47,"end":51,"cssClass":"pl-en"}],[{"start":16,"end":34,"cssClass":"pl-s"},{"start":36,"end":49,"cssClass":"pl-s1"},{"start":49,"end":50,"cssClass":"pl-c1"},{"start":50,"end":63,"cssClass":"pl-s1"}],[{"start":15,"end":75,"cssClass":"pl-c"}],[],[{"start":8,"end":31,"cssClass":"pl-c"}],[{"start":8,"end":10,"cssClass":"pl-k"},{"start":11,"end":28,"cssClass":"pl-s1"},{"start":29,"end":31,"cssClass":"pl-c1"},{"start":32,"end":34,"cssClass":"pl-s"}],[{"start":12,"end":29,"cssClass":"pl-s1"},{"start":30,"end":31,"cssClass":"pl-c1"},{"start":32,"end":37,"cssClass":"pl-en"},{"start":38,"end":55,"cssClass":"pl-s1"}],[],[{"start":8,"end":25,"cssClass":"pl-c"}],[{"start":8,"end":12,"cssClass":"pl-s1"},{"start":13,"end":14,"cssClass":"pl-c1"},{"start":15,"end":29,"cssClass":"pl-en"},{"start":30,"end":31,"cssClass":"pl-s1"}],[],[{"start":8,"end":15,"cssClass":"pl-c"}],[{"start":8,"end":12,"cssClass":"pl-s1"},{"start":13,"end":14,"cssClass":"pl-c1"},{"start":15,"end":19,"cssClass":"pl-s1"},{"start":20,"end":26,"cssClass":"pl-s1"}],[{"start":8,"end":12,"cssClass":"pl-k"},{"start":13,"end":18,"cssClass":"pl-s1"},{"start":19,"end":26,"cssClass":"pl-en"}],[{"start":12,"end":15,"cssClass":"pl-k"},{"start":16,"end":19,"cssClass":"pl-s1"},{"start":20,"end":22,"cssClass":"pl-c1"},{"start":23,"end":27,"cssClass":"pl-s1"}],[{"start":16,"end":21,"cssClass":"pl-s1"},{"start":22,"end":23,"cssClass":"pl-c1"},{"start":24,"end":30,"cssClass":"pl-s1"},{"start":31,"end":49,"cssClass":"pl-s1"},{"start":50,"end":55,"cssClass":"pl-en"},{"start":56,"end":57,"cssClass":"pl-s1"},{"start":58,"end":64,"cssClass":"pl-s1"},{"start":66,"end":69,"cssClass":"pl-s1"}],[{"start":16,"end":19,"cssClass":"pl-s1"},{"start":20,"end":24,"cssClass":"pl-s1"},{"start":25,"end":32,"cssClass":"pl-s"},{"start":34,"end":35,"cssClass":"pl-c1"},{"start":36,"end":41,"cssClass":"pl-s1"}],[{"start":16,"end":18,"cssClass":"pl-k"},{"start":19,"end":22,"cssClass":"pl-s1"},{"start":23,"end":27,"cssClass":"pl-s1"},{"start":28,"end":31,"cssClass":"pl-en"},{"start":32,"end":44,"cssClass":"pl-s"},{"start":46,"end":48,"cssClass":"pl-c1"},{"start":49,"end":53,"cssClass":"pl-c1"}],[{"start":20,"end":23,"cssClass":"pl-s1"},{"start":24,"end":28,"cssClass":"pl-s1"},{"start":29,"end":41,"cssClass":"pl-s"},{"start":43,"end":44,"cssClass":"pl-c1"},{"start":45,"end":78,"cssClass":"pl-s"},{"start":66,"end":77,"cssClass":"pl-s1"},{"start":66,"end":67,"cssClass":"pl-kos"},{"start":67,"end":72,"cssClass":"pl-s1"},{"start":76,"end":77,"cssClass":"pl-kos"}],[{"start":16,"end":20,"cssClass":"pl-k"}],[{"start":20,"end":23,"cssClass":"pl-s1"},{"start":24,"end":28,"cssClass":"pl-s1"},{"start":29,"end":41,"cssClass":"pl-s"},{"start":43,"end":45,"cssClass":"pl-c1"},{"start":46,"end":82,"cssClass":"pl-s"},{"start":48,"end":50,"cssClass":"pl-cce"},{"start":70,"end":81,"cssClass":"pl-s1"},{"start":70,"end":71,"cssClass":"pl-kos"},{"start":71,"end":76,"cssClass":"pl-s1"},{"start":80,"end":81,"cssClass":"pl-kos"}],[],[{"start":8,"end":66,"cssClass":"pl-c"}],[{"start":8,"end":10,"cssClass":"pl-k"},{"start":11,"end":32,"cssClass":"pl-s1"}],[{"start":12,"end":16,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-c1"},{"start":19,"end":23,"cssClass":"pl-en"},{"start":24,"end":30,"cssClass":"pl-en"},{"start":31,"end":37,"cssClass":"pl-k"},{"start":38,"end":39,"cssClass":"pl-s1"},{"start":41,"end":42,"cssClass":"pl-s1"},{"start":43,"end":47,"cssClass":"pl-s1"},{"start":48,"end":55,"cssClass":"pl-s"},{"start":57,"end":58,"cssClass":"pl-c1"},{"start":59,"end":76,"cssClass":"pl-s1"},{"start":78,"end":82,"cssClass":"pl-s1"}],[{"start":8,"end":12,"cssClass":"pl-k"}],[{"start":12,"end":16,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-c1"},{"start":19,"end":23,"cssClass":"pl-s1"}],[],[{"start":8,"end":30,"cssClass":"pl-c"}],[{"start":8,"end":17,"cssClass":"pl-s1"},{"start":18,"end":19,"cssClass":"pl-c1"},{"start":21,"end":24,"cssClass":"pl-s1"},{"start":25,"end":29,"cssClass":"pl-s1"},{"start":30,"end":42,"cssClass":"pl-s"},{"start":44,"end":47,"cssClass":"pl-k"},{"start":48,"end":51,"cssClass":"pl-s1"},{"start":52,"end":54,"cssClass":"pl-c1"},{"start":55,"end":59,"cssClass":"pl-s1"}],[],[{"start":8,"end":23,"cssClass":"pl-c"}],[{"start":8,"end":21,"cssClass":"pl-s1"},{"start":22,"end":23,"cssClass":"pl-c1"},{"start":24,"end":28,"cssClass":"pl-en"},{"start":29,"end":32,"cssClass":"pl-en"},{"start":33,"end":37,"cssClass":"pl-s1"},{"start":39,"end":48,"cssClass":"pl-s1"}],[{"start":8,"end":21,"cssClass":"pl-s1"},{"start":22,"end":26,"cssClass":"pl-en"},{"start":27,"end":30,"cssClass":"pl-s1"},{"start":30,"end":31,"cssClass":"pl-c1"},{"start":31,"end":37,"cssClass":"pl-k"},{"start":38,"end":39,"cssClass":"pl-s1"},{"start":41,"end":42,"cssClass":"pl-s1"},{"start":43,"end":44,"cssClass":"pl-c1"},{"start":46,"end":50,"cssClass":"pl-s1"},{"start":51,"end":58,"cssClass":"pl-s"},{"start":61,"end":68,"cssClass":"pl-s1"},{"start":68,"end":69,"cssClass":"pl-c1"},{"start":69,"end":73,"cssClass":"pl-c1"}],[{"start":8,"end":12,"cssClass":"pl-s1"},{"start":14,"end":23,"cssClass":"pl-s1"},{"start":24,"end":25,"cssClass":"pl-c1"},{"start":26,"end":30,"cssClass":"pl-en"},{"start":31,"end":34,"cssClass":"pl-en"},{"start":35,"end":36,"cssClass":"pl-c1"},{"start":36,"end":49,"cssClass":"pl-s1"}],[],[{"start":8,"end":33,"cssClass":"pl-c"}],[{"start":8,"end":14,"cssClass":"pl-k"},{"start":15,"end":24,"cssClass":"pl-v"}],[{"start":12,"end":13,"cssClass":"pl-s1"},{"start":13,"end":14,"cssClass":"pl-c1"},{"start":14,"end":15,"cssClass":"pl-s1"}],[{"start":12,"end":23,"cssClass":"pl-s1"},{"start":23,"end":24,"cssClass":"pl-c1"},{"start":24,"end":28,"cssClass":"pl-s1"}],[{"start":12,"end":16,"cssClass":"pl-s1"},{"start":16,"end":17,"cssClass":"pl-c1"},{"start":17,"end":21,"cssClass":"pl-s1"},{"start":22,"end":26,"cssClass":"pl-s1"}],[{"start":12,"end":16,"cssClass":"pl-s1"},{"start":16,"end":17,"cssClass":"pl-c1"},{"start":17,"end":21,"cssClass":"pl-s1"},{"start":22,"end":26,"cssClass":"pl-s1"}],[{"start":12,"end":21,"cssClass":"pl-s1"},{"start":21,"end":22,"cssClass":"pl-c1"},{"start":22,"end":31,"cssClass":"pl-s1"}],[{"start":12,"end":32,"cssClass":"pl-s1"},{"start":32,"end":33,"cssClass":"pl-c1"},{"start":33,"end":37,"cssClass":"pl-s1"},{"start":38,"end":58,"cssClass":"pl-s1"}],[]],"csv":null,"csvError":null,"dependabotInfo":{"showConfigurationBanner":false,"configFilePath":null,"networkDependabotPath":"/THUDM/ImageReward/network/updates","dismissConfigurationNoticePath":"/settings/dismiss-notice/dependabot_configuration_notice","configurationNoticeDismissed":false,"repoAlertsPath":"/THUDM/ImageReward/security/dependabot","repoSecurityAndAnalysisPath":"/THUDM/ImageReward/settings/security_analysis","repoOwnerIsOrg":true,"currentUserCanAdminRepo":false},"displayName":"image_reward.py","displayUrl":"https://github.com/THUDM/ImageReward/blob/main/sdwebui/image_reward.py?raw=true","headerInfo":{"blobSize":"4.14 KB","deleteInfo":{"deleteTooltip":"Fork this repository and delete the file"},"editInfo":{"editTooltip":"Fork this repository and edit the file"},"ghDesktopPath":"https://desktop.github.com","gitLfsPath":null,"onBranch":true,"shortPath":"3d445c1","siteNavLoginPath":"/login?return_to=https%3A%2F%2Fgithub.com%2FTHUDM%2FImageReward%2Fblob%2Fmain%2Fsdwebui%2Fimage_reward.py","isCSV":false,"isRichtext":false,"toc":null,"lineInfo":{"truncatedLoc":"121","truncatedSloc":"105"},"mode":"file"},"image":false,"isCodeownersFile":null,"isValidLegacyIssueTemplate":false,"issueTemplateHelpUrl":"https://docs.github.com/articles/about-issue-and-pull-request-templates","issueTemplate":null,"discussionTemplate":null,"language":"Python","languageID":303,"large":false,"loggedIn":true,"newDiscussionPath":"/THUDM/ImageReward/discussions/new","newIssuePath":"/THUDM/ImageReward/issues/new","planSupportInfo":{"repoIsFork":null,"repoOwnedByCurrentUser":null,"requestFullPath":"/THUDM/ImageReward/blob/main/sdwebui/image_reward.py","showFreeOrgGatedFeatureMessage":null,"showPlanSupportBanner":null,"upgradeDataAttributes":null,"upgradePath":null},"publishBannersInfo":{"dismissActionNoticePath":"/settings/dismiss-notice/publish_action_from_dockerfile","dismissStackNoticePath":"/settings/dismiss-notice/publish_stack_from_file","releasePath":"/THUDM/ImageReward/releases/new?marketplace=true","showPublishActionBanner":false,"showPublishStackBanner":false},"renderImageOrRaw":false,"richText":null,"renderedFileInfo":null,"tabSize":8,"topBannersInfo":{"overridingGlobalFundingFile":false,"globalPreferredFundingPath":null,"repoOwner":"THUDM","repoName":"ImageReward","showInvalidCitationWarning":false,"citationHelpUrl":"https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files","showDependabotConfigurationBanner":false,"actionsOnboardingTip":null},"truncated":false,"viewable":true,"workflowRedirectUrl":null,"symbols":{"timedOut":false,"notAnalyzed":false,"symbols":[{"name":"unload_image_reward_model","kind":"function","identStart":978,"identEnd":1003,"extentStart":974,"extentEnd":1040,"fullyQualifiedName":"unload_image_reward_model","identUtf16":{"start":{"lineNumber":33,"utf16Col":4},"end":{"lineNumber":33,"utf16Col":29}},"extentUtf16":{"start":{"lineNumber":33,"utf16Col":0},"end":{"lineNumber":34,"utf16Col":33}}},{"name":"Script","kind":"class","identStart":1049,"identEnd":1055,"extentStart":1043,"extentEnd":4236,"fullyQualifiedName":"Script","identUtf16":{"start":{"lineNumber":37,"utf16Col":6},"end":{"lineNumber":37,"utf16Col":12}},"extentUtf16":{"start":{"lineNumber":37,"utf16Col":0},"end":{"lineNumber":120,"utf16Col":9}}},{"name":"title","kind":"function","identStart":1081,"identEnd":1086,"extentStart":1077,"extentEnd":1157,"fullyQualifiedName":"Script.title","identUtf16":{"start":{"lineNumber":38,"utf16Col":8},"end":{"lineNumber":38,"utf16Col":13}},"extentUtf16":{"start":{"lineNumber":38,"utf16Col":4},"end":{"lineNumber":39,"utf16Col":63}}},{"name":"show","kind":"function","identStart":1167,"identEnd":1171,"extentStart":1163,"extentEnd":1210,"fullyQualifiedName":"Script.show","identUtf16":{"start":{"lineNumber":41,"utf16Col":8},"end":{"lineNumber":41,"utf16Col":12}},"extentUtf16":{"start":{"lineNumber":41,"utf16Col":4},"end":{"lineNumber":42,"utf16Col":19}}},{"name":"ui","kind":"function","identStart":1220,"identEnd":1222,"extentStart":1216,"extentEnd":2192,"fullyQualifiedName":"Script.ui","identUtf16":{"start":{"lineNumber":44,"utf16Col":8},"end":{"lineNumber":44,"utf16Col":10}},"extentUtf16":{"start":{"lineNumber":44,"utf16Col":4},"end":{"lineNumber":64,"utf16Col":57}}},{"name":"run","kind":"function","identStart":2202,"identEnd":2205,"extentStart":2198,"extentEnd":4236,"fullyQualifiedName":"Script.run","identUtf16":{"start":{"lineNumber":66,"utf16Col":8},"end":{"lineNumber":66,"utf16Col":11}},"extentUtf16":{"start":{"lineNumber":66,"utf16Col":4},"end":{"lineNumber":120,"utf16Col":9}}}]}},"copilotInfo":{"notices":{"codeViewPopover":{}},"userAccess":{"accessAllowed":false,"hasSubscriptionEnded":false,"orgHasCFBAccess":false,"userHasCFIAccess":false,"userHasOrgs":false,"userIsOrgAdmin":false,"userIsOrgMember":false,"business":null,"featureRequestInfo":{"showFeatureRequest":true,"alreadyRequested":false,"featureName":"copilot_for_business","requestPath":"/orgs/THUDM/member_feature_request"}}},"csrf_tokens":{"/THUDM/ImageReward/branches":{"post":"DqePMAYrzjnRmqcZvz0je0BcHrcAGWJbgY6ClINRa3oRo1ns3yQM88dDgxZohbk9j_8s-7kVBP6P8tBim7Bjww"}}},"title":"ImageReward/sdwebui/image_reward.py at main · THUDM/ImageReward"}
    NameError: name 'true' is not defined

**Comment by tongyx361** [comment]
I'm sorry that I have not seen an error message in a similar format.
Could you please provide some guidance on how to reproduce this error?
