### ISSUE TITLE
About embedding selection of reward model

### ISSUE THREAD

**Issue by yining-mao** [THUDM/ImageReward#52]
Thank you for the great work! I just have a small question regarding the training and inference stage of the reward model. In the encode_pair function in [train/src/ImageReward.py](https://github.com/THUDM/ImageReward/blob/main/train/src/ImageReward.py) you are using `last_hidden_state[:, -1, :]` of the embedding, but in encode_data function and in the inference stage in [ImageReward/ImageReward.py](https://github.com/THUDM/ImageReward/blob/main/ImageReward/ImageReward.py) you are using `last_hidden_state[:,0,:]`. Why are they different? What is the intention of using the first or the last dimension? Thanks a lot!

**Comment by xujz18** [comment]
Thanks for pointing this out, there was a mis-edit when we were organizing our training code and it has now been corrected. They should all be `last_hidden_state[:,0,:]`.
