### ISSUE TITLE
not connection

### ISSUE THREAD

**Issue by gaogao2002** [THUDM/ImageReward#55]
Run the code below:
import ImageReward as RM
model = RM.load('ImageReward-v1.0')

but it will emerge some mistakes below:
LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

And then I download the " ImageReward.pt" on my own device, but it will emerge teh same mistake as before, what happend.?
![微信图片_20230909002332](https://github.com/THUDM/ImageReward/assets/120021873/6aed438f-dc9e-41e1-ba7a-9365b6801f2a)

**Comment by xujz18** [comment]
My guess is that the path where you loaded "ImageReward.pt" doesn't match your jupyter and it didn't find the file.
