### ISSUE TITLE
缺陷分类对应的图片

### ISSUE THREAD

**Issue by wzczc** [THUDM/ImageReward#75]
![image](https://github.com/THUDM/ImageReward/assets/94534877/6e5d71f5-3451-415a-af1e-98ea64af222e)
作者您好，感谢您的工作！想问一下这张图上每种问题下对应的具体图片是哪些？您有对应的文档记录吗？

**Comment by xujz18** [comment]
[problem_data.json](https://github.com/THUDM/ImageReward/files/14981948/problem_data.json)
You can refer to this json file, which has the same image path as DiffusionDB.
可以参考这个json文件，其图片路径和DiffusionDB是一样的。
