### ISSUE TITLE
(Webui) Image reward info text does not show like in demo video

### ISSUE THREAD

**Issue by kappa54m** [THUDM/ImageReward#91]
When I load the script in Stable Diffusion WebUI, I expect to see the image reward below the generated image panel as demonstrated in the [demo video](https://github.com/THUDM/ImageReward?tab=readme-ov-file#demo-video).
However, when I generated an image on the [lastest webui commit](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/82a973c04367123ae98bd9abdf80d9eda9b910e2) with the script, I don't see the image reward on the UI.

**Comment by kappa54m** [comment]
I would appreciate a review of my [pull request](https://github.com/THUDM/ImageReward/pull/92) addressing this issue.

**Comment by xujz18** [comment]
Cool! Thanks a lot!
